### ISSUE TITLE
About Organizr - Layout broken at 1440p

### ISSUE THREAD

**Issue by merson316** [causefx/Organizr#136]
Hey, 

Minor bug with the layout of the About page when viewed on high res monitors. Below screenshot is 1440p. 

![image](https://cloud.githubusercontent.com/assets/26346341/23823962/b574f716-0665-11e7-8cb6-f16699221844.png)

Thanks.

**Comment by causefx** [comment]
crap! what browser?

**Comment by merson316** [comment]
Chrome 57.0.2987.98.

**Comment by causefx** [comment]
fixed it, I will push a commit out later on :)

thanks for bringing it up

**Comment by merson316** [comment]
Hey,

This is still an issue (excatly the same as the screenshot above) after the updating and clearing the cache.

**Comment by causefx** [comment]
clear your cache, sorry.

**Comment by causefx** [comment]
or just pull up css/style.css and refresh it

**Comment by merson316** [comment]
Didn't change. As a sanity check i tried Edge over Chrome and that appears the same.

**Comment by causefx** [comment]
let me see mine

**Comment by causefx** [comment]
![image](https://cloud.githubusercontent.com/assets/16184466/23837058/45ae8ea8-073f-11e7-98df-6ae24b9e8572.png)

**Comment by causefx** [comment]
on style.css

what does this portion say for you?

```
.cbp_tmtimeline > li .cbp_tmtime {
  display: block;
  width: 25%;
  padding-right: 10%;
  position: absolute;
}
```

**Comment by merson316** [comment]
Right, for some reason the sytle.css was owned by root and not www-data, so it may have never updated! Manually fixed the file and all is good. :)

**Comment by causefx** [comment]
awesome
