### ISSUE TITLE
homepage jellyfin : open existing jellifin tab (iframe)

### ISSUE THREAD

**Issue by toxic0berliner** [causefx/Organizr#1633]
I got the jellifin item on the homepage working but I cannot find a way for organizr to not open a new tab when I click on one item in there and instead "open" the existing jellyfin tab that is an iframe for me.

Am I missing something here or is it just a missing feature that I should ask for in feathub ?

**Comment by HalianElf** [comment]
If you have the `Jellyfin Tab Name` set in Misc Options on the Homepage Item, it should be opening in the tab.

**Comment by toxic0berliner** [comment]
It is set properly, but still it opens in a new tab. Maybe there is a specific syntax since my jellyfin iframe/tab is in a category. Tried media/jellyfin but it doesn't seem to work

**Comment by HalianElf** [comment]
It should just need to be the name of the tab and that's in (believe it's case sensitive too). Did you also refresh the whole site after setting it?

**Comment by toxic0berliner** [comment]
Ok, got it working, thanks, turns out I had to fill both the Jellyfin HomePage url AND the Jellyfin WAN url in the other options.
Now on the homepage when I click the purple fish I do get the jellyfin tab opening to the proper page.

Well, to be honest, it works only the first time, meaning if the jellyfin tab is not already open. As soon as the jellyfin tab has already been opened, it stops showing the page of the clicked item, but at least it opens the jellyfin tab.

I'm doing this in windows10 with the latest firefox stable, but I do have a Blackberry Amethyst installed that might be not transperent in this issue since I might have installed Amethyst javascript with Abyss CSS... I'll mostly click tha only once so no further issue for me, just an info if you feel that could be a real issue.

Otherwise you can consider this closed for me ;) Thanks a lot !

**Comment by CAPS3** [comment]
Hi Toxic0berliner, 

I have the same issue with it only working the first time. I found if you close the jellyfin tab using the little "x" in the top left hand corner, near the hamburger menu, (near the logo and refresh button), and _then_ go back to the homepage and use the Jellyfin link, it'll work again. 

I agree it would be nice if it was able to refresh the jellyfin tab and 'overwrite' the last followed link as I believe it had worked that way at some stage in the past.

**Comment by Facinorous-420** [comment]
I m coming across this as well in my Organizr instance.
It doesn't just happen to the media buttons. 

It's anytime you try to change the iframes url to a jellyfin url other than the dashboard.

It returns to whatever page your jellyfin tab was on.

My jellyfin settings and homepage items are set right afaik, as sso works for the Jellyfin tab

**Comment by causefx** [comment]
the fix should be ready tomorrow

**Comment by Facinorous-420** [comment]
> the fix should be ready tomorrow

Amazing! Thanks for the quick updates! 
Look forward to testing this when the fix rolls out.

**Comment by causefx** [comment]
fixed in master.

**Comment by Facinorous-420** [comment]
I am updated to 2.1.496 and still having this issue happen on my end.
Sorry about not getting to testing this sooner, had been busy prior. 

Nothing happens in the browser console when I click the media button on the home page item, except saying it is switching to the media tab. (Which it does). Though it does not switch to that item's page in my Jellyfin, only keeps it at the last browsed page. When I inspect the element to the Jellyfin media button on the home page item, and grab the url it points to, I can paste it directly in my browser in a new tab and it opens that items page.
I am not sure what else to test, or where to look in terms to getting to the bottom of this issue.

**Comment by Facinorous-420** [comment]
> 
> 
> fixed in master.

I am updated to 2.1.496 and still having this issue happen on my end.
Sorry about not getting to testing this sooner, had been busy prior.

Nothing happens in the browser console when I click the media button on the home page item, except saying it is switching to the media tab. (Which it does). Though it does not switch to that item's page in my Jellyfin, only keeps it at the last browsed page. When I inspect the element to the Jellyfin media button on the home page item, and grab the url it points to, I can paste it directly in my browser in a new tab and it opens that items page.
I am not sure what else to test, or where to look in terms to getting to the bottom of this issue.

**Comment by Facinorous-420** [comment]
@causefx 
I have done some testing and found out this issue is 100% how Jellyfin interacts inside of iFrames.

I wrote some quick html and js on a site that contained just an iframe and a button that changed the iframe source. The original url of the iFrame was my base Jellyfin URL, and the button changed it to a specific item in my library. 

When I was at my jellyfin homepage the button worked and brought me to that item.
Though, when I was already within an item in my Jellyfin library (or on any other page other than the homepage) it stayed on that page and did not switch the iFrame properly to the other items page
This is exactly how it's been working in Organizr, so that proves there is nothing wrong in Organizr causing this issue.

This is something that should be discussed with the Jellyfin team as maybe they would know of a solution.

**Comment by Facinorous-420** [comment]
Opened an issue in the JF repo regarding this. Hopefully we can get to the bottom of this 🙏

https://github.com/jellyfin/jellyfin/issues/6496

**Comment by causefx** [comment]
Thanks @Facinorous-420

**Comment by causefx** [comment]
Closing this, as this is in Jellyfin's hands now - Reply or open this back up if something happens on their end.
