### ISSUE TITLE
QBitTorrent Tab won't filter out completed downloads

### ISSUE THREAD

**Issue by mephisto3478** [causefx/Organizr#1740]
###### Operating System: Linux (Docker)
<hr>

##### Problem Description:

In the settings of the QBitTorrent Homepage Tab, the option "Hide completed" shows up twice but none of it seems to work. I can toggle both or just one of them, completed downloads still won't be filtered out of the Tab.
<hr>

##### Reproduction Steps:

Settings/Tab Editor/Homepage-Elements/QBitTorrent/
Toggle "Hide completed"

**Comment by causefx** [comment]
i fixed the toggle in dev.

**Comment by causefx** [comment]
please test now that it is pushed to master

**Comment by jiznon** [comment]
Updated to 2.1.111 but no change. Toggled the setting of and back on and restarted server but issue persists.
