### ISSUE TITLE
Does not run on PHP 8.1

### ISSUE THREAD

**Issue by aniqueta** [causefx/Organizr#1877]
###### Operating System: macOS
<hr>

##### Problem Description:

Organizr does not work using PHP 8.1, but does with PHP 8.0. Fresh install has same issue. 
<hr>

##### Reproduction Steps:

Update to PHP 8.1 using existing installation and/or do new installation on system using PHP 8.1.
<hr>

#### Errors on screen?  If so paste here:

```

Deprecated: Return type of Tightenco\Collect\Support\Collection::offsetExists($key) should either be compatible with ArrayAccess::offsetExists(mixed $offset): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/organizr/api/vendor/tightenco/collect/src/Collect/Support/Collection.php on line 1911

Deprecated: Return type of Tightenco\Collect\Support\Collection::offsetGet($key) should either be compatible with ArrayAccess::offsetGet(mixed $offset): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/organizr/api/vendor/tightenco/collect/src/Collect/Support/Collection.php on line 1922

Deprecated: Return type of Tightenco\Collect\Support\Collection::offsetSet($key, $value) should either be compatible with ArrayAccess::offsetSet(mixed $offset, mixed $value): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/organizr/api/vendor/tightenco/collect/src/Collect/Support/Collection.php on line 1934

Deprecated: Return type of Tightenco\Collect\Support\Collection::offsetUnset($key) should either be compatible with ArrayAccess::offsetUnset(mixed $offset): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/organizr/api/vendor/tightenco/collect/src/Collect/Support/Collection.php on line 1949

Deprecated: Return type of Tightenco\Collect\Support\Collection::count() should either be compatible with Countable::count(): int, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/organizr/api/vendor/tightenco/collect/src/Collect/Support/Collection.php on line 1890

Deprecated: Return type of Tightenco\Collect\Support\Collection::getIterator() should either be compatible with IteratorAggregate::getIterator(): Traversable, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/organizr/api/vendor/tightenco/collect/src/Collect/Support/Collection.php on line 1869

Deprecated: Return type of Tightenco\Collect\Support\Collection::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/organizr/api/vendor/tightenco/collect/src/Collect/Support/Collection.php on line 1838
```

**Comment by aniqueta** [comment]
This issue is still not resolved for me.

**Comment by paxperscientiam** [comment]
The easiest solution is to turn off the deprecation warning.

EG, if you're using Apache like me, you could add this directive to the .htaccess file 
```
php_value error_reporting 24575 # this means enable all reporting except deprecation warnings
```

**Comment by aniqueta** [comment]
> The easiest solution is to turn off the deprecation warning.
> 
> EG, if you're using Apache like me, you could add this directive to the .htaccess file
> 
> ```
> php_value error_reporting 24575 # this means enable all reporting except deprecation warnings
> ```

Thanks for the workaround. Still think this is worth keeping open for a proper solution.

**Comment by paxperscientiam** [comment]
Yeah, "workaround" is more accurate.

**Comment by aniqueta** [comment]
This remains an unresolved issue.

**Comment by paavo** [comment]
any plans to get this fixed?

**Comment by causefx** [comment]
made small change to dev. will merge to master shortly. should fix the errors i believe. Sent from my iPhoneOn Dec 6, 2022, at 10:15 AM, Paavo ***@***.***> wrote:﻿
any plans to get this fixed?

**Comment by Swiftnesses** [comment]
I still see this, was this merged to Master as planned @causefx?

**Comment by paavo** [comment]
@causefx any progress?

**Comment by causefx** [comment]
Yes this was merged to master already. was tested on Windows machine running:
PHP 8.1.11
Organizr 2.1.2400

**Comment by paavo** [comment]
it was fixed, thanks 🎉
