### ISSUE TITLE
Clicking plex now playing items doesn't work

### ISSUE THREAD

**Issue by Fma965** [causefx/Organizr#493]
when clicking on any now playing item or using the search clicking the item doesn't work as it uses app.plex.tv and that doesn't work in a iframe giving this error

Refused to display 'https://app.plex.tv/web/app#!/server/c8d6d1cef5fa2258e368b4abaa9604e6c4427459/details?key=/library/metadata/8018' in a frame because it set 'X-Frame-Options' to 'deny'.

**Comment by Fma965** [comment]
just to confirm this only works when "plex tab" is set to nothing.

**Comment by causefx** [comment]
This option only works if you have plex in a subdomain.  If it doesn't then it will display plex.tv like normal.  This has been fixed.

In the new update it will now show a new message:
![image](https://user-images.githubusercontent.com/16184466/28235485-6597f016-68c3-11e7-95b8-0f4603b5bf89.png)

**Comment by Fma965** [comment]
this still doesn't work from the search on the latest version, leaving the plex tab blank then searching for something results in search results showing but not being clickable.

**Comment by causefx** [comment]
i will take a look, thanks.

p.s. what url does it show?

**Comment by Fma965** [comment]
it just doesn't show anything. you can't click it.

**Comment by Fma965** [comment]
'''
<tr style="cursor: pointer;" class="openTab" opentab="false" href="https://app.plex.tv/web/app#!/server/c8d6d1cef5fa2258e368b4abaa9604e6c4427459/details?key=/library/metadata/8544">
            <th scope="row"><img src="ajax.php?a=plex-image&amp;img=/library/metadata/8544/thumb/1498514173&amp;height=150&amp;width=100&amp;key=8544-search"></th>
            <td class="col-xs-2 nzbtable nzbtable-row" style="vertical-align: middle">Terminator 2: Judgment Day</td>
            <td class="col-xs-3 nzbtable nzbtable-row" style="vertical-align: middle">Sci-Fi</td>
            <td class="col-xs-1 nzbtable nzbtable-row" style="vertical-align: middle">1991</td>
            <td class="col-xs-1 nzbtable nzbtable-row" style="vertical-align: middle">Movie</td>
            <td class="col-xs-3 nzbtable nzbtable-row" style="vertical-align: middle">2015-03-24</td>
            <td class="col-xs-2 nzbtable nzbtable-row" style="vertical-align: middle">Content Rating: R<br>Movie Rating: 9.3</td>
            </tr>'''

that's the HTML i see but i can't click the item still.

**Comment by Fma965** [comment]
I can click it from the plex carousel on the homepage but not the search

**Comment by causefx** [comment]
ok, digging into it now

**Comment by causefx** [comment]
@Fma965 

can you open homepage.php and edit this:

```
$(document).on("click", ".openTab", function(e) {
    if($(this).attr("openTab") === "true") {
        var isActive = parent.$("div[data-content-name^='<?php echo strtolower(PLEXTABNAME);?>']");
        var activeFrame = isActive.children('iframe');
        if(isActive.length === 1){
            activeFrame.attr("src", $(this).attr("href"));
            parent.$("li[name='<?php echo strtolower(PLEXTABNAME);?>']").trigger("click");
        }else{
            parent.$("li[name='<?php echo strtolower(PLEXTABNAME);?>']").trigger("click");
            parent.$("div[data-content-name^='<?php echo strtolower(PLEXTABNAME);?>']").children('iframe').attr("src", $(this).attr("href"));
        }
        e.preventDefault();
    }else{
        var source = $(this).attr("href");
        window.open(source, '_blank');
    }

});
```

**Comment by Fma965** [comment]
I'm actually in the middle of moving servers currently so won't be able to test that for a day or so.

**Comment by causefx** [comment]
it's okay i can test later today

**Comment by Fma965** [comment]
I'm now all on the new server so i can test it out later today.
